restaurant_search/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
]

search/urls.py
from django.urls import path
from .views import SearchDishesView, DetailView

app_name = 'search'

urlpatterns = [
    path('', SearchDishesView.as_view(), name="search"),
    path('restaurant/<str:id>', DetailView.as_view(), name="detail"),
]

search/models.py
from django.db import models

class Restaurant(models.Model):
    ID = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    lat_long = models.CharField(max_length=200)
    other_details = models.JSONField()

    def __str__(self):
        return self.name + " (" + self.location + ")"

class Dishes(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    item = models.CharField(max_length=200)
    price = models.CharField(max_length=50)

    def __str__(self):
        return self.item + " " + self.restaurant.name

search/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from .models import Restaurant, Dishes
import json

class SearchDishesView(View):
    def get(self, request):
        query = request.GET.get('search')
        if query:
            results = Dishes.objects.filter(item__icontains=query)
            return render(request, "search/index.html", {'results': results})
        return render(request, "search/index.html", {'results': None})

class DetailView(View):
    def get(self, request, id):
        result = Restaurant.objects.get(ID=id)
        return render(request, "search/detail.html", {'result': json.loads(result.other_details)})

search/templates/search/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Restaurant Search</title>
</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand">Restaurant</a>
        <form action="{% url 'search:search' %}" class="form-inline">
            <input class="form-control mr-lg-2" name="search" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </nav>
    {% block body %} {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

search/templates/search/detail.html
{% extends "search/base.html" %}

{% block body %}
<div class="container">
    <h1 class="mb-4">{{ result.name }}</h1><hr>
    <div class="row">
        <div class="col-md-6">
            <h3>Cuisine</h3>
            <p>{{ result.cuisines }}</p>
            <h3>Price Range</h3>
            <p> {{ result.price_range }} </p>
        </div>
        <div class="col-md-6">
            <h3>Rating</h3>
            <p class="text-{{ result.user_rating.rating_color }}">{{ result.user_rating.aggregate_rating }} ({{ result.user_rating.rating_text }})</p>
            <h3>Location</h3>
            <p>{{ result.location.address }}, {{ result.location.locality_verbose }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3>More Information</h3>
            <ul class="list-group">
                <li class="list-group-item">Delivery Available: {% if result.is_delivering_now %} Yes {% else %} No {% endif %}</li>
                <li class="list-group-item">Average Cost for Two: {{ result.average_cost_for_two }}</li>
            </ul>
        </div>
    </div>
</div>    
{% endblock %}

search/templates/search/index.html
{% extends "search/base.html" %}

{% block body %}
<div class="container-fluid" style="display: flex;justify-content: space-between;flex-wrap: wrap;flex-direction: row;">
    {% for i in results %}
    <div class="card mt-2" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">{{ i.restaurant.name }}</h5>
          <p class="card-text">
            Dish Name: {{ i.item }}<br>
            Dish Price: {{ i.price }}<br>
            Location: {{ i.restaurant.location }}<br>
          </p>
          <a href="{% url 'search:detail' i.restaurant.ID %}" class="btn btn-primary">View Restaurant Details</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}